#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

rfile=data/rfArtistURL.txt
OUT=data/artistURI.txt

# create file if doesn't exist, otherwise wipe it.
if [ -f "$OUT" ];
then
    echo "Output directory exists. Emptying..."
    rm "$OUT"
    touch "$OUT"
else
    echo "Output directory does NOT exist"
    touch "$OUT"
fi

while read -r line;
do
    # Get spotify URL
    echo "$line"
    spotURL=$(wget -q -O - "$@" "$line" | \
    	grep -oP "SpotifyPlayer.*\Khttps.*\"" | \
    	sed 's/\".*//' || echo "None")
    echo "URL: $spotURL"

    # find album URI
    if [ "$spotURL" = "None" ]
    then
	artistURI="None"
    else
	echo "writing stuff"
	artistURI=$(echo "$spotURL" | \
			grep -oP ".*artist\/\K[0-9a-zA-Z]+")
	echo "$artistURI" >> "$OUT"
    fi

    echo "URI: $artistURI"
    echo ''
done < $rfile
